/* export const SET_MUSIC_URL = 'SET_MUSIC_URL';

export const SET_COVER_IMG_URL = 'SET_COVER_IMG_URL'; */

export const SET_SONG_INFO = 'SET_SONG_INFO';

export const SET_DURATION = 'SET_DURATION';

export const SET_IS_PLAYING = 'SET_IS_PLAYING';

export const SET_CURRENT_TIME = 'SET_CURRENT_TIME';

export const SET_LIKE_LIST = 'SET_LIKE_LIST';

export const UPDATE_RECENT_PLAYLIST = 'UPDATE_RECENT_PLAYLIST';

export const UPDATE_LOGIN_STATUS = 'UPDATE_LOGIN_STATUS';
